feat: home page
docgeni/docgeni pull request #202
Opened 2021-07-12 06:29 UTC by wszgrcy

2021-07-15 02:38 UTC, why520crazy requested changes

2021-07-15 02:38 UTC, why520crazy commented on packages/core/src/builders/navs-builder.ts
> +    private async buildHomeMeta() {
这个地方建议直接修改 `buildDocDirNavs` 函数， 返回 homeMeta 数据，存储在 localesDocsNavsMap 即可，可能不用单独存储一个 `localesHomeMetaMap`

其次有几个逻辑现在不满足：
1. `index.md` 没有写 FrontMatter 数据，但是只要有内容，也可以在首页展示，如果 Meta 数据有 Features 展示 Features， 有 Hero 展示 Hero
2. `index.md` 也需要支持 hidden 属性，现在是不支持的

2021-07-15 02:38 UTC, why520crazy commented on packages/template/src/pages/home/home.component.html
> +  <div class="dg-extra-content" [innerHTML]="extraContent"></div>
对于首页的 Markdown 内容，需要支持：
1. 和普通文档的样式一样，现在样式是不匹配的，代码段，标题，引用等等
2. 需要支持直接展示内置组件的，比如 `<example name="xxx" />` 

综上所述，建议使用 `dg-content-viewer` 组件，这个组件目前是传入一个 HTML URL 地址，然后远程加载渲染的，如果首页不希望有加载的过程可以修改这个组件支持 content 传入，然后直接渲染，但是这个功能可以往后，1和2两个需求是需要的。

2021-07-15 02:38 UTC, why520crazy commented on packages/template/src/styles/button.scss
> +}
对于按钮来说，大小设置使用 `dg-button-size` 和 .dg-btn-sm 设置放一起

目前默认按钮高度是 `36px` ，我们可以简单给大小分个类
- xsm：28px
- sm：32px
- md：36px
- lg：40px
- xlg：44px

首页的按钮直接使用 xlg 大小的。

2021-07-15 02:38 UTC, why520crazy commented on packages/template/src/styles/button.scss
> +}
outline 使用 `dg-button-outline-variant` mixin 设置

2021-07-15 02:38 UTC, why520crazy commented on packages/template/src/styles/button.scss
> +@mixin btn-square-radius($border-radius) {
改成 `dg-button-radius-variant` 移动到 `mixins/button.scss` 文件中

2021-07-15 02:38 UTC, why520crazy commented on packages/template/src/styles/button.scss
> +}
可以把这个去掉，按钮的类型虽然有 square，但是不是 border-radius:0 ， 默认的 border-radius 为 4px 其实就是方形的，当什么都不设置默认就是 square

2021-07-15 02:41 UTC, why520crazy commented
最后贯穿整体的两个小问题：
1. 格式问题，函数之间加换行，代码保持整洁，我有强迫症，看着难受，你不修改，我早晚也会帮你修改，你看 Angular 源码应该也挺多的了，没有注意到别人的细节问题么，当然这个不是格式化可以解决的，因为不是任何地方都需要换行，如果说服不了你，你可以不修改
2. Home Meta 建议补充上测试，单元测试不好加，可以先在 CLI 的 `test/build.spec.ts` 加一个整体测试，断言一下 homeMeta 数据即可

2021-07-15 02:47 UTC, why520crazy requested changes

2021-07-15 02:47 UTC, why520crazy commented on docs/index.md
>    description: A modern documentation generator for doc and Angular Lib
这里先改成：`开箱即用的 Angular 组件文档生成工具`

2021-07-15 02:47 UTC, why520crazy commented on packages/template/src/interfaces/config.ts
> +        backgroundColor?: string;
Actions 的属性比较多了，建议单独加一个 interface HeroAction

2021-07-15 02:47 UTC, why520crazy commented on packages/template/src/pages/home/home.component.scss
> +            border: none;
去掉按钮的大小设置，使用 `dg-btn-xlg` 大小

2021-07-15 06:30 UTC, wszgrcy commented on packages/template/src/styles/button.scss
> +}
按这么设计原来的sm其实是xsm?

2021-07-15 06:50 UTC, wszgrcy commented on packages/core/src/builders/navs-builder.ts
> +    private async buildHomeMeta() {
增加hidden属性?每一个字段上都加上这个?

2021-07-15 23:23 UTC, why520crazy commented on packages/template/src/styles/button.scss
> +}
> 按这么设计原来的sm其实是xsm?

是的

2021-07-15 23:26 UTC, why520crazy commented on packages/core/src/builders/navs-builder.ts
> +    private async buildHomeMeta() {
> 增加hidden属性?每一个字段上都加上这个?

我们现在所有文档都支持一个属性，看文档介绍

https://docgeni.org/configuration/front-matter

2021-07-19 06:31 UTC, wszgrcy commented on packages/template/src/styles/button.scss
> +}
那么宽度,字体大小,行高,倒角是怎么规定的?

2021-08-25 01:15 UTC, why520crazy approved these changes

2021-08-25 01:18 UTC, merged