feat: stackblitz support
docgeni/docgeni pull request #276
Opened 2021-11-04 03:44 UTC by wszgrcy

2021-11-04 08:00 UTC, why520crazy requested changes

2021-11-04 08:00 UTC, why520crazy commented on .docgenirc.js
> +    }
这里是否也可以改成让用户自己在 `assets/stack-blitz/package.json` 配置，然后动态加载。只需要配置 `dependencies`即可

```
// package.json
dependencies: {
            '@angular/animations': '~10.2.4',
            '@angular/cdk': '^10.2.7',
            '@angular/common': '~10.2.4',
            '@angular/compiler': '~10.2.4',
            '@angular/core': '~10.2.4',
            '@angular/forms': '~10.2.4',
            '@angular/platform-browser': '~10.2.4',
            '@angular/platform-browser-dynamic': '~10.2.4',
            rxjs: '~6.5.4',
            'zone.js': '~0.10.2',
            '@docgeni/alib': '0.0.1'
        }
```

2021-11-04 08:06 UTC, wszgrcy commented on packages/core/src/docgeni-host.ts
> +                    files.push(relative(path, item));
添加这个方法的原因是因为原来的方法返回的类型是`PathFragment`而这个方法由于需要拼接,不得不转换为string,虽然两种类型声明几乎一样,但是容易破坏之前的结构.

2021-11-04 08:07 UTC, why520crazy requested changes

2021-11-04 08:07 UTC, why520crazy commented on packages/template/src/shared/example-viewer/example-viewer.component.html
> +    <a class="action-item" title="Open example in new tab" target="_blank" (click)="openStackBlitz()"
title 改成 `Open example in StackBlitz`

2021-11-04 10:19 UTC, wszgrcy commented on packages/core/src/builders/library-builder.ts
> +        await this.addEmitFile(resolve(sharedExampleDir, 'bundle.json'), content);
打包的好处是让运行时简易化处理,就算不打包,也要维护一个资源文件.json,先请求这个,然后再去请求对应的资源,那么这个资源文件.json是否也会同步更新?这个也是和打包一个问题,
毕竟前端是无法知道有哪些资源的

2021-11-04 10:29 UTC, wszgrcy commented on packages/template/src/services/example.service.ts
> +}
> 如果`styles.scss`、`angular.json` 是运行时直接获取`assets/stack-blitz`下的内容，那么这里的很多文件都可以改成运行时直接获取，这样的好处是用户可以自定义，比如`index.html`、`main.ts`。
> 
> 当然为了让用户更简单的使用，我们可以提供一些默认的`index.html`、`main.ts`,用户想自定义可以覆盖，对于动态生成的内容，`app.component.ts` 直接按照现在的方式生成即可。
> 
> 这里外层的 `module.ts` 其实是 ExamplesModule，建议改成`examples.module.ts` 并移动到 src 目录中去。

改名不好改,因为设计就是读整个文件夹然后再插入的,我觉得也是和整个例子保持同一性

2021-11-04 12:55 UTC, why520crazy commented on packages/core/src/docgeni-host.ts
> +                    files.push(relative(path, item));
本身`PathFragment`就是继承的 string，如果需要拼接自己转换一下即可，加上`recursively `默认是`false`和现在的逻辑一样应该不会破坏，本身`getFiles`就应该需要支持获取所有子文件夹和子文件。

2021-11-04 13:00 UTC, why520crazy commented on packages/core/src/builders/library-builder.ts
> +        await this.addEmitFile(resolve(sharedExampleDir, 'bundle.json'), content);
维护一个静态资源.json 也没有太大的必要，获取哪些通用的文件是我们定义好的，比如`angular.json`、`index.html`、`src/styles.scss`、`main.ts`，也就是这几个通用的文件，所以在前端直接定死获取这些文件夹即可。

第一步写死就可以了，将来需要的话可以根据文件夹的文件生成一个`resources.json`，然后动态获取。

2021-11-04 13:01 UTC, why520crazy commented on packages/template/src/services/example.service.ts
> +}
这个如果不好改先这样吧，文件夹的结构不好改，但是名字应该可以修改的，提交到 stack-blitz 的时候重新设置一下即可 `module.ts` => `examples.module.ts`

2021-11-08 11:03 UTC, why520crazy requested changes

2021-11-08 11:03 UTC, why520crazy commented on packages/core/src/docgeni-host.ts
> +        const subPaths = [];
尽量不要定义这种 any 的类型，`const subPaths: PathFragment[] = [];`

2021-11-09 03:41 UTC, wszgrcy commented on packages/core/src/docgeni-host.ts
> +    getFiles(path: string, options?: GetDirsOrFilesOptions): Promise<string[]>;
文件路径被合并,用不了这个加上递归后必须合并子文件夹中的路径,之前不就跟你说过就因为这个原因我才把那个方法分开写的吗?你又让合并进去了

2021-11-09 03:48 UTC, wszgrcy commented on packages/core/src/angular/site-builder.ts
> +        );
main与index可以在文件夹里添加替换(没有添加的话就是默认的),之所以在服务中有的原因是因为这些都是入口,正常情况下不会有人进行修改自定义

2021-11-09 07:06 UTC, why520crazy approved these changes

2021-11-09 07:08 UTC, merged