Osp 227/chen
docgeni/docgeni pull request #303
Opened 2021-12-28 08:24 UTC by wszgrcy

2021-12-30 05:51 UTC, why520crazy requested changes

2021-12-30 05:51 UTC, why520crazy commented on packages/template/src/pages/component-viewer/api/component-api.component.html
> +            <td class="dg-api-properties-name-cell" [attr.rowspan]="method.rowSpan" *ngIf="method.rowSpan">
把 函数展示的表格样式加一个 `dg-api-methods-table` 吧，严格区分一下，这样就不会影响 properties 表格
`dg-api-methods-name-th`  `dg-api-methods-type-th` `dg-api-methods-description-th`

2021-12-30 05:51 UTC, why520crazy commented on packages/ngdoc/test/fixtures/full/input/service1.serivce.ts
> +export class Service1Service {
示例中的 Logger 服务就是为测试服务使用的，建议把 Service1Service 移除，直接使用 Logger 吧

2021-12-30 05:51 UTC, why520crazy commented on packages/ngdoc/src/types/declarations.ts
> +    rowSpan?: number;
rowSpan 是渲染表格而使用的参数，并不是函数文档本身具备的属性，可以去掉，对于重载函数感觉可以每个重载显示一行，因为每个重载函数的签名不一定一样，比如泛型

```
open<T>()
open<T, TResult>()
```

2021-12-30 05:58 UTC, why520crazy requested changes

2021-12-30 05:58 UTC, why520crazy commented on packages/template/src/pages/component-viewer/api/component-api.component.html
> +                  返回值:
参数和返回值需要考虑多语言

2022-01-04 01:51 UTC, wszgrcy commented on packages/ngdoc/src/parser/utils.ts
> +        description: ts.displayPartsToString(symbol.getDocumentationComment(checker)),
这个主要是为了想省点事,少些一个转换,然后改的,现在是全改成comment吗

2022-01-05 03:38 UTC, why520crazy approved these changes

2022-01-05 03:38 UTC, merged