Osp 2/chen
docgeni/docgeni pull request #90
Opened 2021-03-12 06:12 UTC by wszgrcy

2021-03-12 10:52 UTC, why520crazy requested changes

2021-03-12 10:52 UTC, why520crazy commented on packages/cli/src/schematics/ng-add/init-docgenirc.ts
> +                    format('.docgenirc.js', 'babel')
建议不要使用 prettier 给 .docgenirc.js 格式化，我们默认一个格式即可，用户自己用啥格式都行

2021-03-12 11:22 UTC, wszgrcy commented on packages/cli/src/schematics/ng-add/init-docgenirc.ts
> +                    format('.docgenirc.js', 'babel')
因为不格式化生成的` .docgenirc.js`不正规.....,一个是用json字符串话属性带引号,一个是格式化缩进,这个在任务中我提到过也有截图,如果通过逻辑实现这些我觉得可能不会太稳定(假如没有已有逻辑的话)

2021-03-15 05:38 UTC, why520crazy approved these changes

2021-03-15 05:39 UTC, merged